source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'FOSRESTApp', :exclusive => true do
  pod "FOSRest", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "FOSRest", :path => "../"
end
