source 'https://github.com/CocoaPods/Specs.git'

target 'FOSFoundationApp', :exclusive => true do
  pod "FOSFoundation", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "FOSFoundation", :path => "../"
end
