platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'FOSRESTApp' do
  pod "fosrest", :path => "../"
end

target 'Tests' do
  pod "fosrest", :path => "../"
end

