language: objective-c

env:
    SDK:iphonesimulator
    SDK:iphoneos

script: xcodebuild build -workspace Example/FOSREST.xcworkspace -scheme FOSREST-Example -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.2'

