language: objective-c

env:
    SDK:iphonesimulator
    SDK:iphoneos

before_install:
    - export LANG=en_US.UTF-8
    - env
    - locale
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - pod --version
    - pod setup --silent
    - pod repo update --silent

script:
    - pod lib lint
    - cd Example
    - pod update
    - xcodebuild build -workspace FOSREST.xcworkspace -scheme FOSREST-Example -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.1'

