#line 2 "/Users/david/Library/Developer/Xcode/DerivedData/FOSREST-fodkpoehriibrldqgafemiosbmld/Build/Intermediates/Pods.build/Debug-iphonesimulator/Pods-FOSRESTApp-fosrest.build/DerivedSources/FOSAdapterBinding.yy.m"

#line 4 "/Users/david/Library/Developer/Xcode/DerivedData/FOSREST-fodkpoehriibrldqgafemiosbmld/Build/Intermediates/Pods.build/Debug-iphonesimulator/Pods-FOSRESTApp-fosrest.build/DerivedSources/FOSAdapterBinding.yy.m"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 75
#define YY_END_OF_BUFFER 76
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[507] =
    {   0,
        7,    7,   76,   74,    2,    2,   74,   74,   74,   74,
       13,   14,   18,   12,   17,    7,   11,   10,   74,   74,
       74,   74,   74,   74,   74,   74,   74,   74,   74,   74,
       74,   74,   74,   74,   74,   74,    8,   19,   15,   20,
       16,    0,    6,    0,    1,    0,    4,    0,    5,    7,
        9,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    8,    3,    4,    0,   37,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   57,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   59,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    3,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   54,    0,    0,    0,    0,    0,
        0,    0,   58,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       39,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   42,   60,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   40,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       43,    0,    0,   21,    0,    0,    0,    0,    0,    0,
       44,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   56,    0,   53,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   55,    0,    0,   25,    0,    0,
        0,    0,   35,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   32,    0,
        0,    0,    0,    0,    0,    0,   28,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,   52,    0,
       38,   36,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   50,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   34,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   51,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   24,    0,    0,    0,    0,    0,   66,   71,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   22,    0,    0,    0,    0,
       26,    0,    0,    0,    0,    0,    0,    0,   73,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   41,    0,    0,   31,
       30,    0,    0,    0,    0,    0,    0,   49,    0,    0,
       72,    0,    0,    0,   29,    0,    0,    0,    0,    0,
       23,    0,    0,   64,    0,    0,    0,   61,    0,    0,
        0,    0,    0,   27,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   65,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   68,
       33,    0,    0,    0,   70,    0,    0,    0,   63,    0,
       69,   48,    0,    0,   67,   45,    0,   46,    0,   62,

        0,    0,    0,    0,   47,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    6,    1,    1,    7,    8,
        9,    1,   10,   11,    1,   12,    1,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   14,   15,    1,
        1,    1,    1,    1,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
        1,    1,    1,    1,   42,   43,   44,   44,   44,   44,

       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,   45,   46,   47,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[48] =
    {   0,
        1,    1,    1,    1,    1,    2,    1,    1,    1,    1,
        1,    1,    3,    1,    1,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    1,    4,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[515] =
    {   0,
        0,    0,  529,  530,  530,  530,  524,  524,  520,  518,
      530,  530,  530,  530,  530,  511,  509,  530,   29,   33,
       22,  502,  492,  500,  499,  499,  483,   28,  486,   30,
       35,  495,   47,  490,   43,  493,    0,  530,  530,  530,
      530,  508,  530,  508,  530,    0,    0,  503,  530,  496,
      530,  492,  480,  471,  471,  475,  476,  472,  481,   26,
       42,  465,  483,  456,  467,  475,  473,  452,  473,  473,
      457,  456,  454,   48,  459,  471,  458,  455,  465,  456,
      465,    0,    0,    0,  450,  438,  446,  458,  458,  450,
      433,  458,  453,  437,  429,  446,  530,  450,  452,  438,

      446,   38,  446,  422,  443,  428,  426,  530,  440,  443,
      422,  424,  437,  422,  434,  420,  436,  409,  429,    0,
      414,  428,  423,  404,  421,  402,  426,  407,  406,  407,
      408,  403,  417,  401,  393,  416,  404,  396,  415,  395,
      396,  390,  530,  403,  391,  405,  400,  381,  402,  391,
      401,  384,  401,  387,  396,  376,  397,  377,  383,  373,
      386,  389,  388,  377,  376,  381,  371,  368,   61,  362,
      530,  366,  365,  369,  378,  367,  359,  371,  360,  373,
      362,  372,  354,  369,  368,  363,  353,  352,  366,  347,
      349,  359,  347,  350,  530,  530,  338,  353,  356,  333,

      341,  349,  353,  351,  350,  336,  350,  530,  351,  324,
      346,  331,  343,  332,  326,  323,  330,  316,  322,  323,
      530,  326,  326,  530,  333,  317,  324,  308,  333,  329,
      530,  318,  312,  324,  320,  314,  300,  323,  311,  323,
      311,  530,   51,  530,  318,  294,  306,  292,  313,  305,
      314,  288,  309,  309,  530,  296,  306,  530,  295,  293,
      299,  287,  530,  297,  303,  300,  301,  297,  297,  284,
      294,  297,  283,  269,  280,  275,   61,  266,  267,  282,
      281,  285,  279,  267,   50,  270,  269,  270,  256,  277,
      260,  271,  270,  269,  250,  260,  248,  260,  268,  254,

      257,  262,  254,  263,   53,  240,  252,  251,  530,  250,
      530,  530,  261,  242,  256,  253,  243,  246,  237,  242,
      241,  232,  230,  247,  232,  225,  530,  244,  236,  238,
      228,  225,  239,  238,  241,  237,  220,  232,  229,  228,
      218,  530,  234,  230,  228,  225,  227,  225,  211,  210,
      207,  530,  207,  200,  208,  210,  214,  209,  202,  199,
      209,  212,  197,  201,  199,  186,  194,  192,  530,  530,
      201,  182,  207,  180,  181,  200,  177,   54,  202,  187,
      200,  178,  179,  184,  179,  530,  192,  181,  183,  192,
      530,  178,  168,  174,  178,  176,  167,  185,  530,  183,

      164,  179,  162,  176,  162,  172,  156,  168,  157,  170,
      161,  166,  154,  155,  165,  164,  530,  148,  158,  530,
      530,  157,  147,  155,  144,  161,  147,  530,  135,  154,
      530,  157,  152,  131,  530,  135,  140,  138,  125,  149,
      530,  138,  142,  530,  128,  131,  128,  530,  127,  140,
      129,  124,  120,  530,  121,  134,  122,  110,  127,  126,
      115,  128,  112,  530,  113,  125,  118,  126,  113,  118,
      122,  119,  104,  104,  116,   99,  112,  109,  102,  530,
      530,   89,   90,   94,   94,   96,   93,   99,  530,  104,
      530,  530,  104,  102,  530,   56,   81,  530,   91,  530,

       67,   57,   62,   38,  530,  530,   99,  103,  106,  110,
      112,   50,  114,  116
    } ;

static yyconst flex_int16_t yy_def[515] =
    {   0,
      506,    1,  506,  506,  506,  506,  507,  508,  509,  510,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  511,  506,  506,  506,
      506,  507,  506,  508,  506,  512,  513,  510,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  511,  514,  513,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,

      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  514,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,

      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,

      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,

      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,

      506,  506,  506,  506,  506,    0,  506,  506,  506,  506,
      506,  506,  506,  506
    } ;

static yyconst flex_int16_t yy_nxt[578] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
        4,   24,   25,   26,   27,    4,   28,    4,   29,   30,
       31,    4,   32,   33,   34,   35,    4,   36,    4,    4,
        4,   37,   38,   37,   39,   40,   41,   52,   55,   58,
       71,   66,   93,   83,   59,   53,   56,   67,   69,   94,
       95,  137,   70,   54,   72,  109,   75,  138,   57,   76,
       73,   78,  505,   79,  110,   80,   96,  202,  272,  111,
      273,  303,  112,  312,  203,  333,  334,  399,  304,  498,
      504,  313,  503,  204,  205,  400,  502,  499,  206,   42,

       42,   42,   42,   44,   44,   44,   44,   47,  501,   47,
       48,   48,   48,   48,   82,   82,   84,   84,  120,  120,
      500,  497,  496,  495,  494,  493,  492,  491,  490,  489,
      488,  487,  486,  485,  484,  483,  482,  481,  480,  479,
      478,  477,  476,  475,  474,  473,  472,  471,  470,  469,
      468,  467,  466,  465,  464,  463,  462,  461,  460,  459,
      458,  457,  456,  455,  454,  453,  452,  451,  450,  449,
      448,  447,  446,  445,  444,  443,  442,  441,  440,  439,
      438,  437,  436,  435,  434,  433,  432,  431,  430,  429,
      428,  427,  426,  425,  424,  423,  422,  421,  420,  419,

      418,  417,  416,  415,  414,  413,  412,  411,  410,  409,
      408,  407,  406,  405,  404,  403,  402,  401,  398,  397,
      396,  395,  394,  393,  392,  391,  390,  389,  388,  387,
      386,  385,  384,  383,  382,  381,  380,  379,  378,  377,
      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,
      366,  365,  364,  363,  362,  361,  360,  359,  358,  357,
      356,  355,  354,  353,  352,  351,  350,  349,  348,  347,
      346,  345,  344,  343,  342,  341,  340,  339,  338,  337,
      336,  335,  332,  331,  330,  329,  328,  327,  326,  325,
      324,  323,  322,  321,  320,  319,  318,  317,  316,  315,

      314,  311,  310,  309,  308,  307,  306,  305,  302,  301,
      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  285,  284,  283,  282,  281,
      280,  279,  278,  277,  276,  275,  274,  271,  270,  269,
      268,  267,  266,  265,  264,  263,  262,  261,  260,  259,
      258,  257,  256,  255,  254,  253,  252,  251,  250,  249,
      248,  247,  246,  245,  244,  243,  242,  241,  240,  239,
      238,  237,  236,  235,  234,  233,  232,  231,  230,  229,
      228,  227,  226,  225,  224,  223,  222,  221,  220,  219,
      218,  217,  216,  215,  214,  213,  212,  211,  210,  209,

      208,  207,  201,  200,  199,  198,  197,  196,  195,  194,
      193,  192,  191,  190,  189,  188,  187,  186,  185,  184,
      183,  182,  181,  180,  179,  178,  177,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  164,
      163,  162,  161,  160,  159,  158,  157,  156,  155,  154,
      153,  152,  151,  150,  149,  148,  147,  146,  145,  144,
      143,  142,  141,  140,  139,  136,  135,  134,  133,  132,
      131,  130,  129,  128,  127,  126,  125,  124,  123,  122,
      121,  119,  118,  117,  116,  115,  114,  113,  108,  107,
      106,  105,  104,  103,  102,  101,  100,   99,   98,   97,

       92,   91,   90,   89,   88,   87,   86,   85,   50,   49,
       45,   43,   81,   77,   74,   68,   65,   64,   63,   62,
       61,   60,   51,   50,   49,   46,   45,   43,  506,    3,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506
    } ;

static yyconst flex_int16_t yy_chk[578] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   19,   20,   21,
       31,   28,   60,  512,   21,   19,   20,   28,   30,   60,
       61,  102,   30,   19,   31,   74,   33,  102,   20,   33,
       31,   35,  504,   35,   74,   35,   61,  169,  243,   74,
      243,  277,   74,  285,  169,  305,  305,  378,  277,  496,
      503,  285,  502,  169,  169,  378,  501,  496,  169,  507,

      507,  507,  507,  508,  508,  508,  508,  509,  499,  509,
      510,  510,  510,  510,  511,  511,  513,  513,  514,  514,
      497,  494,  493,  490,  488,  487,  486,  485,  484,  483,
      482,  479,  478,  477,  476,  475,  474,  473,  472,  471,
      470,  469,  468,  467,  466,  465,  463,  462,  461,  460,
      459,  458,  457,  456,  455,  453,  452,  451,  450,  449,
      447,  446,  445,  443,  442,  440,  439,  438,  437,  436,
      434,  433,  432,  430,  429,  427,  426,  425,  424,  423,
      422,  419,  418,  416,  415,  414,  413,  412,  411,  410,
      409,  408,  407,  406,  405,  404,  403,  402,  401,  400,

      398,  397,  396,  395,  394,  393,  392,  390,  389,  388,
      387,  385,  384,  383,  382,  381,  380,  379,  377,  376,
      375,  374,  373,  372,  371,  368,  367,  366,  365,  364,
      363,  362,  361,  360,  359,  358,  357,  356,  355,  354,
      353,  351,  350,  349,  348,  347,  346,  345,  344,  343,
      341,  340,  339,  338,  337,  336,  335,  334,  333,  332,
      331,  330,  329,  328,  326,  325,  324,  323,  322,  321,
      320,  319,  318,  317,  316,  315,  314,  313,  310,  308,
      307,  306,  304,  303,  302,  301,  300,  299,  298,  297,
      296,  295,  294,  293,  292,  291,  290,  289,  288,  287,

      286,  284,  283,  282,  281,  280,  279,  278,  276,  275,
      274,  273,  272,  271,  270,  269,  268,  267,  266,  265,
      264,  262,  261,  260,  259,  257,  256,  254,  253,  252,
      251,  250,  249,  248,  247,  246,  245,  241,  240,  239,
      238,  237,  236,  235,  234,  233,  232,  230,  229,  228,
      227,  226,  225,  223,  222,  220,  219,  218,  217,  216,
      215,  214,  213,  212,  211,  210,  209,  207,  206,  205,
      204,  203,  202,  201,  200,  199,  198,  197,  194,  193,
      192,  191,  190,  189,  188,  187,  186,  185,  184,  183,
      182,  181,  180,  179,  178,  177,  176,  175,  174,  173,

      172,  170,  168,  167,  166,  165,  164,  163,  162,  161,
      160,  159,  158,  157,  156,  155,  154,  153,  152,  151,
      150,  149,  148,  147,  146,  145,  144,  142,  141,  140,
      139,  138,  137,  136,  135,  134,  133,  132,  131,  130,
      129,  128,  127,  126,  125,  124,  123,  122,  121,  119,
      118,  117,  116,  115,  114,  113,  112,  111,  110,  109,
      107,  106,  105,  104,  103,  101,  100,   99,   98,   96,
       95,   94,   93,   92,   91,   90,   89,   88,   87,   86,
       85,   81,   80,   79,   78,   77,   76,   75,   73,   72,
       71,   70,   69,   68,   67,   66,   65,   64,   63,   62,

       59,   58,   57,   56,   55,   54,   53,   52,   50,   48,
       44,   42,   36,   34,   32,   29,   27,   26,   25,   24,
       23,   22,   17,   16,   10,    9,    8,    7,    3,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
#line 2 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
//
//  The MIT License (MIT)
//
//  Copyright (c) 2015 FOS Services, LLC
//
//  Permission is hereby granted, free of charge, to any person obtaining a copy
//  of this software and associated documentation files (the "Software"), to deal
//  in the Software without restriction, including without limitation the rights
//  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//  copies of the Software, and to permit persons to whom the Software is
//  furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in all
//  copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//  SOFTWARE.
//

// NOTE: ***
//
// At this time there's a bug in CocoaPods (https://github.com/CocoaPods/CocoaPods/issues/3127)
// where it will pass CFLAGS to flex/bison, which causes compilation to fail.  Thus, the .[ch]
// files are also checked in, which are used to build the actual lexer and compiler.
//
// Any modification made to this file will necessitate the manual re-generation of the .[ch]
// files from these sources.
//
// NOTE: ***

    #import "FOSREST_Internal.h"
    #import "y.tab.h"
    #include <stdio.h>

    #undef YYSIZE_T
    #define YYSIZE_T yytype_int16

extern void yyerror(char* s, ...);

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wconversion"
#pragma clang diagnostic ignored "-Wunused-function"
#pragma clang diagnostic ignored "-Wunneeded-internal-declaration"

int yycolumn = 1;

NSMutableString *currentLine = nil;

static void update_loc() {
    static int curr_line = 1;
    static int curr_col  = 1;

    yylloc.first_line   = curr_line;
    yylloc.first_column = curr_col;

    {
        char * s;
        for (s = yytext; *s != '\0'; s++){
            if (*s == '\n'){
                curr_line++;
                curr_col = 1;

                currentLine = [NSMutableString string];
            }
            else {
                curr_col++;
            }
        }
    }

    yylloc.last_line   = curr_line;
    yylloc.last_column = curr_col-1;

    NSString *curText = [NSString stringWithCString:yytext encoding:NSASCIIStringEncoding];

    if (currentLine == nil) {
        currentLine = [NSMutableString string];
    }

    [currentLine appendString:curText];
}

#define YY_USER_ACTION update_loc();

#line 836 "/Users/david/Library/Developer/Xcode/DerivedData/FOSREST-fodkpoehriibrldqgafemiosbmld/Build/Intermediates/Pods.build/Debug-iphonesimulator/Pods-FOSRESTApp-fosrest.build/DerivedSources/FOSAdapterBinding.yy.m"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 93 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"


#line 1021 "/Users/david/Library/Developer/Xcode/DerivedData/FOSREST-fodkpoehriibrldqgafemiosbmld/Build/Intermediates/Pods.build/Debug-iphonesimulator/Pods-FOSRESTApp-fosrest.build/DerivedSources/FOSAdapterBinding.yy.m"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 507 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 530 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 95 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ /* skip comments */ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 96 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ /* skip spaces */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 98 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ yylval.string = yytext; return SHARED_BINDING_IDENTIFIER; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 99 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ yylval.string = yytext; return IDENTIFIER; }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 100 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ yylval.string = yytext; return STRING_LITERAL; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 101 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ yylval.string = yytext; return STRING_LITERAL; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 102 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ yylval.string = yytext; return INTEGER_LITERAL; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 103 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ yylval.string = yytext; return STRING_CONSTANT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 105 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return SEP; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 106 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return SEMI; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 107 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return COLON; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 108 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return COMMA; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 109 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return LPAREN; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 110 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return RPAREN; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 111 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return LBRACE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 112 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return RBRACE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 113 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return DOT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 114 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return PLUS; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 115 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return TIC; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 116 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return PIPE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 118 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return ADAPTER; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 119 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return URL_BINDINGS; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 120 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return SHARED_BINDINGS; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 122 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return URL_BINDING; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 123 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return BASE_URL; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 124 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return HEADER_FIELDS; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 125 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return TIMEOUT_INTERVAL; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 127 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return LIFECYCLE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 128 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return LIFECYCLE_STYLE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 129 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return REQUEST_METHOD; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 130 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return REQUEST_FORMAT; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 131 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return END_POINT; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 132 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return END_POINT_PARAMETERS; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 133 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return CMO_BINDING; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 135 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return ENTITIES; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 136 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return ATTRIBUTES; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 137 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return ALL; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 138 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return ALL_EXCEPT; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 140 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return LOGIN; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 141 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return LOGOUT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 142 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return PASSWORD_RESET; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 143 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return CREATE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 144 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return UPDATE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 145 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return DESTROY; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 146 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return RETRIEVE_SERVER_RECORD; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 147 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return RETRIEVE_SERVER_RECORDS; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 148 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return RETRIEVE_SERVER_RECORD_COUNT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 149 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return RETRIEVE_RELATIONSHIP; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 151 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return BINDING_OPTIONS; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 152 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return ONE_TO_ONE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 153 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return ONE_TO_MANY; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 154 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return UNORDERED; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 155 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return ORDERED; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 157 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return JSON; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 158 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return WEBFORM; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 159 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return NO_DATA; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 161 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return GET; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 162 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return POST; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 163 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return PUT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 164 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return DELETE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 166 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return JSON_WRAPPER_KEY; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 167 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return JSON_RECEIVE_WRAPPER_KEY; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 168 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return JSON_SEND_WRAPPER_KEY; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 169 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return BULK_WRAPPER_KEY; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 170 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return ATTRIBUTE_BINDINGS; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 171 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return ID_ATTRIBUTE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 172 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return RECEIVE_ONLY_ATTRIBUTE; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 173 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return SEND_ONLY_ATTRIBUTE; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 175 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return RELATIONSHIP_BINDINGS; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 176 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return RELATIONSHIP_BINDING; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 178 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return JSON_BINDING; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 179 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return JSON_ID_BINDING; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 180 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ return RELATIONSHIPS; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 182 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
{ yyerror("Unknown token: %s", yytext); yyterminate(); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 184 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"
ECHO;
	YY_BREAK
#line 1483 "/Users/david/Library/Developer/Xcode/DerivedData/FOSREST-fodkpoehriibrldqgafemiosbmld/Build/Intermediates/Pods.build/Debug-iphonesimulator/Pods-FOSRESTApp-fosrest.build/DerivedSources/FOSAdapterBinding.yy.m"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 507 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 507 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 506);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 184 "/Users/david/Repository/FOSPods/FOSREST/Pod/Classes/Private/FOSAdapterBinding.lm"



int yywrap() {
    return -1;
}

void yyreset_state() {
    BEGIN(INITIAL);
}

#pragma clang diagnostic pop

